Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -91,33 +91,31 @@ health_check:
       if [ "$CI_COMMIT_BRANCH" == "main" ]; then
         echo "Loading Docker image for main branch...";
         docker load -i image/main_${CI_PIPELINE_ID}_docker_image.tar;
-        docker images;
         IMAGE_NAME="$DOCKER_IMAGE_NAME";
       else
         echo "Loading Docker image for non-main branch...";
         docker load -i image/${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}_docker_image.tar;
-        docker images;
-        IMAGE_NAME=${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}_docker_image.tar;
+        IMAGE_NAME="$LOCAL_IMAGE_NAME";
       fi
 
       # Run the image in a container and wait for it to be healthy
-      # echo "Starting Docker container for health check...";
-      # docker run -d --name health_check_container -p 8080:8080 $IMAGE_NAME;
-      # sleep 10;
+      echo "Starting Docker container for health check...";
+      docker run -d --name health_check_container -p 8080:8080 $IMAGE_NAME;
+      sleep 10;
 
       # # Check health endpoint
-      # echo "Checking health endpoint...";
-      # HEALTH_STATUS=$(curl --silent --max-time 30 http://localhost:8080/actuator/health_check)
+      echo "Checking health endpoint...";
+      HEALTH_STATUS=$(curl --silent --max-time 30 http://localhost:8080/actuator/health_check)
 
       # # Print health status
-      # echo "Health check response: $HEALTH_STATUS";
+      echo "Health check response: $HEALTH_STATUS";
 
       # # Fail the job if health check doesn't pass (i.e., non-200 response)
-      # if [[ "$HEALTH_STATUS" != *"UP"* ]]; then
-      #   echo "Health check failed!";
-      #   exit 1;
-      # fi
+      if [[ "$HEALTH_STATUS" != *"UP"* ]]; then
+        echo "Health check failed!";
+        exit 1;
+      fi
 
       # # Clean up by stopping and removing the container
-      # docker stop health_check_container;
-      # docker rm health_check_container;
+      docker stop health_check_container;
+      docker rm health_check_container;
